<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVABr6Hc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVABr6Hc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVABr6Hc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVABr6Hc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVABr6Hc\App_KernelDevDebugContainer([
    'container.build_hash' => 'VABr6Hc',
    'container.build_id' => 'b5d09f4a',
    'container.build_time' => 1617296800,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVABr6Hc');
