<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJndrpVh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJndrpVh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJndrpVh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJndrpVh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJndrpVh\App_KernelDevDebugContainer([
    'container.build_hash' => 'JndrpVh',
    'container.build_id' => '1a5cc99c',
    'container.build_time' => 1617554388,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJndrpVh');
